### PR TITLE
.gitignore ignore-rev

### PR DESCRIPTION
**Pull request by jsugarman**
## What
Ignore file used locally to store revs for ignoring when using `git blame`

Useful to ignore rubocop fixes commits locally when you
are wanting to trace history using git blame.

To implement locally:

```
cd [root of codebase]

cat > .git-blame-ignore-revs << EOF

90a8f3c03106bc66d6ea777f615a944e8d6f7ac2
EOF

git config blame.ignoreRevsFile .git-blame-ignore-revs
```

## Checklist

Before you ask people to review this PR:

- Tests and rubocop should be passing: `bundle exec rake`
- Github should not be reporting conflicts; you should have recently run `git rebase main`.
- There should be no unnecessary whitespace changes. These make diffs harder to read and conflicts more likely.
- The PR description should say what you changed and why, with a link to the JIRA story.
- You should have looked at the diff against main and ensured that nothing unexpected is included in your changes.
- You should have checked that the commit messages say why the change was made.

### CODE REVIEW

**Review by cpjmcquillan — CHANGES_REQUESTED** [review]
I usually keep things that aren't project specific (e.g `.vscode`) in my global `.gitignore` instead. I've been using this for a while, and had added it there until now.

Having said that, I actually think there is a pretty good argument for us checking this in to the repo. These are some of the benefits I can think of:

- We can review changes and ensure ignores are relevant
- Everyone gets the benefits
- GitHub will apply it too

It's easy enough to override locally if you want to un-ignore things (or ignore things) in your own special way. 

What do you think?

**Comment by colinbruce** [comment]
Was about to post something similar to @cpjmcquillan :+1:
https://www.stefanjudis.com/today-i-learned/how-to-exclude-commits-from-git-blame/#fun-fact%3A-github-picks-up-%60.git-blame-ignore-revs%60 why not let Github ignore 80 file commits that replace single quotes with doubles?!

It means the git history is cleaner too, I can see an argument for going back and adding a lot of rubocop or location refactors being added to this file!

**Comment by jsugarman** [comment]
I like the idea of having a `.git-blame-ignore-revs` file per repo and checked in:

I can change this to add mine now?

```
# Run this command to always ignore formatting commits in `git blame`
# git config blame.ignoreRevsFile .git-blame-ignore-revs

# Changing single-quote to double-quote
90a8f3c03106bc66d6ea777f615a944e8d6f7ac2
```

**Comment by cpjmcquillan** [comment]
> I like the idea of having a .git-blame-ignore-revs file per repo

Just to clarify @jsugarman, when you have a global `.gitignore` file it just means the contents are ignored by git. It doesn't mean you can't have a specific `.git-blame-ignore-revs` file per project.

> I can change this to add mine now?

Yeah, go for it! (That's what mine is locally at the minute).

> I can see an argument for going back and adding a lot of rubocop or location refactors being added to this file!

@colinbruce 💯

**Comment by jsugarman** [comment]
I had actually added it yesterday inadvertently when I merged another PR 😬 
https://github.com/ministryofjustice/laa-apply-for-legal-aid/blob/main/.git-blame-ignore-revs

**Comment by cpjmcquillan** [comment]
> I had actually added it yesterday inadvertently when I merged another PR 😬

galaxy-brain

**Pull request closed without merging**
