### PR TITLE
Fix: Improve task list test handling

### PR DESCRIPTION
**Pull request by colinbruce**
## What

Add a new set of rspec matchers that can be passed a group, task, and optionally, a state to determine
the current state of the task list.

`have_completed_task(:group, :task_name)`
`have_not_started_task(:group, :task_name)`
and, underlying them,
`have_task_in_state((:group, :task_name, :state)`

## Checklist

Before you ask people to review this PR:

- Tests and rubocop should be passing: `bundle exec rake`
- Github should not be reporting conflicts; you should have recently run `git rebase main`.
- There should be no unnecessary whitespace changes. These make diffs harder to read and conflicts more likely.
- The PR description should say what you changed and why, with a link to the JIRA story.
- You should have looked at the diff against main and ensured that nothing unexpected is included in your changes.
- You should have checked that the commit messages say why the change was made.

### CODE REVIEW

**Review by cpjmcquillan — APPROVED** [review]
🎉

**Comment by colinbruce** [comment]
Marked as `on_hold` I'll find and replace all uses of the old style and update this PR, while keeping it rebased :+1:

**Comment by colinbruce** [comment]
@cpjmcquillan are you happy with all the changes in a single PR?

**Review by cpjmcquillan — APPROVED** [review]
Yeah I think it makes sense to adopt it wholesale now.

Nice work!

**Pull request merged**
