### PR TITLE
Update Ruby to v3.1.3

### PR DESCRIPTION
**Pull request by cpjmcquillan**
Ruby 3.1.3 was [released on 24 November
2022](https://www.ruby-lang.org/en/news/2022/11/24/ruby-3-1-3-released/).

This updates the Ruby version to this latest patch.

### CODE REVIEW

**Comment by cpjmcquillan** [comment]
There is no `ruby:3.1.3-alpine3.14` image, and [`wkhtmltopdf`](https://github.com/wkhtmltopdf/wkhtmltopdf) has been [removed from alpine 3.15 and beyond](https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.15.0#Significant_removals). 

It looks like `wkhtmltopdf` is no longer maintained either.

We currently use [`wicked_pdf`](https://github.com/mileszs/wicked_pdf) (which relies on `wkhtmltopdf`) to generate means, merits, and bank transaction reports. 

How do we want to proceed?

**Comment by colinbruce** [comment]
Try spiking a replacement for wkhtmltopdf (alpine suggest `weasyprint`?) or even replacing wicked_pdf?

**Comment by cpjmcquillan** [comment]
Truly the upgrade the keeps on giving...

Bumping our CircleCI image from `cimg/ruby:3.1.2-browsers` to `cimg/ruby:3.1.3-browsers` takes our node version from `v16.14.2` to `v.18.12.1`.

[webpacker doesn't work on node17](https://github.com/rails/webpacker/issues/3235) though (unless we upgrade to v6.rc6, but we're currently on v5 still).

[We should be able to swap Node versions](https://support.circleci.com/hc/en-us/articles/360051656632-Swap-node-version-on-CircleCI-convenience-image), but I haven't tried it yet.

**Review by jsugarman — APPROVED** [review]
👍 For merging into your other branch this looks fine to me

**Pull request merged**
