### PR TITLE
Remove db backup cronjobs

### PR DESCRIPTION
**Pull request by naseberry**
## What

[Remove hourly db backup cronjobs](https://dsdmoj.atlassian.net/browse/AP-4061)

Remove the cron jobs involved in storing and clearing the db backups

## Why

Amazon, in theory, allows a point-in-time recovery making the backup files a resource drain that we are unlikely to need

## TO-DO

- [x] Manually run the backup cleaner to remove any legacy backups

## Checklist

Before you ask people to review this PR:

- Tests and rubocop should be passing: `bundle exec rake`
- Github should not be reporting conflicts; you should have recently run `git rebase main`.
- There should be no unnecessary whitespace changes. These make diffs harder to read and conflicts more likely.
- The PR description should say what you changed and why, with a link to the JIRA story.
- You should have looked at the diff against main and ensured that nothing unexpected is included in your changes.
- You should have checked that the commit messages say why the change was made.

### CODE REVIEW

**Comment by kmahern** [comment]
Do we need to first check with CP that we able to carry out point in time restores before merging this pr? The ticket says that AWS in theory allows point-in-time restores but my understanding is that this needs to be configured. I have looked in the CP user guide but this only mentions one overnight backup.

**Review by colinbruce — APPROVED** [review]
LGTM :+1:

_Maybe_ we could schedule a point-in-time recovery, the same as the original DR test?

**Comment by naseberry** [comment]
> Do we need to first check with CP that we able to carry out point in time restores before merging this pr? The ticket says that AWS in theory allows point-in-time restores but my understanding is that this needs to be configured. I have looked in the CP user guide but this only mentions one overnight backup.

Quoting CP - "Point-in-time recovery for RDS relies on snapshots, either automated or manual. You can do point-in-time recovery to any point in time within the backup retention period; which is (by default) 7 days."

So yes, PITR is possible with CP's automated snapshots (although we may require CP support)

**Comment by jsugarman** [comment]
> Do we need to first check with CP that we able to carry out point in time restores before merging this pr? The ticket says that AWS in theory allows point-in-time restores but my understanding is that this needs to be configured. I have looked in the CP user guide but this only mentions one overnight backup.

It does look and sound like a combination of an automated daily backup plus point in time recovery (PITR) can allow us to restore an instance of the DB from up to 7 days ago until up to ~5 minutes ago.

I have used the cli to confirm LatestRestorableTime is showing as ~5 minutes ago for Apply production RDS instance. Documentation confirms that a [daily backup is taken](https://aws.amazon.com/rds/features/backup/#:~:text=Amazon%20RDS%20automatically%20creates%20a,known%20as%20the%20backup%20window.) so it sounds like we do not need to take a manual snapshot. But when was the last time a DR scenario was test?

**Pull request merged**
