### PR TITLE
AP-5268: Add primary nav

### PR DESCRIPTION
**Pull request by agoldstone93**
## What

[Link to story](https://dsdmoj.atlassian.net/browse/AP-5268)

Add your applications and search to primary nav, displayed on each page. Add individual primary nav component from moj design system. Additional mixins are added too as they are required.

## Screenshot

Updated page looks like this:

image

## Checklist

Before you ask people to review this PR:

- Tests and rubocop should be passing: `bundle exec rake`
- Github should not be reporting conflicts; you should have recently run `git rebase main`.
- The standards in the [Git Workflow document on Confluence](https://dsdmoj.atlassian.net/wiki/spaces/ATPPB/pages/4602855954/Git+Workflow) should be followed
- There should be no unnecessary whitespace changes. These make diffs harder to read and conflicts more likely.
- The PR description should say what you changed and why, with a link to the JIRA story.
- You should have looked at the diff against main and ensured that nothing unexpected is included in your changes.
- You should have checked that the commit messages say why the change was made.

### CODE REVIEW

**Review by colinbruce — APPROVED** [review]
LGTM 👍 
Shame there isn't a govuk helper for the navigation tree!

**Comment by naseberry** [comment]
> LGTM 👍 Shame there isn't a govuk helper for the navigation tree!

One for UX, but could we use [GOVUK's Service navigation](https://design-system.service.gov.uk/components/service-navigation/) instead?

This would mean less assets to import, and we have the benefit of using the helper from GOVUK Components for Ruby

**Comment by agoldstone93** [comment]
> > LGTM 👍 Shame there isn't a govuk helper for the navigation tree!
> 
> One for UX, but could we use [GOVUK's Service navigation](https://design-system.service.gov.uk/components/service-navigation/) instead?
> 
> This would mean less assets to import, and we have the benefit of using the helper from [GOVUK Components](https://govuk-components.netlify.app/components/service-navigation/) for Ruby

I did raise this but it was decided that we'd go with the MoJ element. I think it's because this work came about by aiming for consistency across teams and that's what everyone else is using. Definitely something to consider though?

**Comment by agoldstone93** [comment]
> @agoldstone93 Be considerate of the sass import order. At present, any shared selector across across our imports means MoJ styles would override GOVUK, then our custom style would then override both the above.

@naseberry That seems like the order we'd want, isn't it?

**Pull request merged**
