### PR TITLE
AP-815-SPIKE Front-end search

### PR DESCRIPTION
**Pull request by MalcolmVonMoJ**
## What

[Link to story](https://dsdmoj.atlassian.net/browse/AP-XXX)

Describe what you did and why.

## Checklist

Before you ask people to review this PR:

- [ ] Tests and rubocop should be passing: `bundle exec rake`
- [ ] Github should not be reporting conflicts; you should have recently run `git rebase master`.
- [ ] There should be no unnecessary whitespace changes. These make diffs harder to read and conflicts more likely.
- [ ] The PR description should say what you changed and why, with a link to the JIRA story.
- [ ] You should have looked at the diff against master and ensured that nothing unexpected is included in your changes.
- [ ] You should have checked that the commit messages say why the change was made.

### CODE REVIEW

**Comment by reggieb** [comment]
This code is fine as far as it goes, but the hard part of searching is not the isolation of matching records, but the ordering by relevance.

**Comment by MalcolmVonMoJ** [comment]
I agree.  But this does the search to the extent as required in the ticket.  The ordering of the rows is already taken care of by sorting.  A more comprehensive search that re-sorted the results would need more code and all the complexity therein.

**Comment by reggieb** [comment]
It's amazing what a bit of sleep can do. I've just remember something - we are already using a JavaScript search library ([JsSearch](https://github.com/bvaughn/js-search)) - see `app/javascript/src/modules/proceedings.js`.

**Comment by mpw5** [comment]
A decision was made to implement this in the back-end, not front-end, so closing this PR.

**Pull request closed without merging**
