### PR TITLE
AP-829 - update GOVUK styles

### PR DESCRIPTION
**Pull request by mpw5**
## What

[Link to story](https://dsdmoj.atlassian.net/browse/AP-829)

Upgrade GOVUK Design System to 3.0.

This contains breaking changes, so I have made a number of fixes in line with recommendations here: https://github.com/alphagov/govuk-frontend/releases/tag/v3.0.0

- fix stylesheet import paths, by adding `/govuk/` to all filepaths
- fix `data-module` elements, by adding `govuk-` as prefix to all
- add new fonts
- use preferred colours
- fix broken menu link, by adding `govuk-` to `js-header-toggle`
- fix appearance of start buttons, by adding a helper method to add the chevron which was previously present but now needs to be manually added
- css changes to fix button highlighting and broken focus state

## Checklist

Before you ask people to review this PR:

- [x] Tests and rubocop should be passing: `bundle exec rake`
- [x] Github should not be reporting conflicts; you should have recently run `git rebase master`.
- [x] There should be no unnecessary whitespace changes. These make diffs harder to read and conflicts more likely.
- [x] The PR description should say what you changed and why, with a link to the JIRA story.
- [x] You should have looked at the diff against master and ensured that nothing unexpected is included in your changes.
- [x] You should have checked that the commit messages say why the change was made.

### CODE REVIEW

**Comment by Kalagan** [comment]
This adds 2 new fonts. Don't we need to remove some old ones?

**Comment by mpw5** [comment]
> This adds 2 new fonts. Don't we need to remove some old ones?

Good point. I'll remove the old ones.

**Comment by Kalagan** [comment]
Could you also modify https://github.com/ministryofjustice/laa-apply-for-legal-aid/blob/master/app/views/layouts/_govuk_base64_fonts.html.erb to use the new fonts?
This partial is used for PDFs and insert the fonts in the page

**Comment by mpw5** [comment]
> Could you also modify https://github.com/ministryofjustice/laa-apply-for-legal-aid/blob/master/app/views/layouts/_govuk_base64_fonts.html.erb to use the new fonts?
> This partial is used for PDFs and insert the fonts in the page

Thanks, I didn't know about that file. I'll change it. 

The design system no longer provides `tabular` fonts. Any thoughts on what I should do with these entries? Remove them? Point them at the regular light/bold fonts?

image

**Comment by Kalagan** [comment]
I think you can remove them

**Pull request merged**
