### PR TITLE
[AP-3184] Use remote github action to delete UAT release

### PR DESCRIPTION
**Pull request by jsugarman**
## What
Use a custom github action in separate repo to delete the UAT release

[Link to story](https://dsdmoj.atlassian.net/browse/AP-3184)

This uses `ministryofjustice/laa-civil-apply-delete-uat-release@v1.0.0` to allow us to 
share the github action logic between all apply service components this

## Checklist

Before you ask people to review this PR:

- Tests and rubocop should be passing: `bundle exec rake`
- Github should not be reporting conflicts; you should have recently run `git rebase main`.
- There should be no unnecessary whitespace changes. These make diffs harder to read and conflicts more likely.
- The PR description should say what you changed and why, with a link to the JIRA story.
- You should have looked at the diff against main and ensured that nothing unexpected is included in your changes.
- You should have checked that the commit messages say why the change was made.

### CODE REVIEW

**Comment by jsugarman** [comment]
test

**Comment by jsugarman** [comment]
test

**Comment by jsugarman** [comment]
test version 2.0.0 of action

**Comment by jsugarman** [comment]
test use of `ministryofjustice/laa-civil-apply-delete-uat-release@v1.0.0`.

**Review by willc-work — APPROVED** [review]

**Pull request merged**
